version: "3.8"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis:6379
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=visit_counter
      - MYSQL_USER=user
      - MYSQL_PASSWORD=your_password
    depends_on:
      - redis
      - mysql

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: visit_counter
      MYSQL_USER: user
      MYSQL_PASSWORD: your_password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10